site_name: project_title
theme: 'material'
extra:
  feature:
    tabs: true
  palette:
    primary: 'green'
    accent: 'green'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'css/extra.css'
google_analytics:
  - 'UA-104338919-3'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - meta
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.arithmatex
repo_name: 'Cognitio'
repo_url: 'https://github.com/LuxAtrumStudio/Cognitio'
pages:
  - 'Home': 'index.md'
  - 'Tutorial':
    - 'Home': 'tutorial/index.md'
  - 'API':
    - 'Home': 'api/index.md'
